# Generated by Django 2.1.2 on 2018-11-05 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20181027_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
